export const mutations = {
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_DATA: 'SET_DATA',
    SET_ACTION_NOTIFY: 'SET_ACTION_NOTIFY',
    FETCH_SIGNED: 'FETCH_SIGNED',
    FETCH_PENDING: 'FETCH_PENDING',
    FETCH_PENDING_BY_OTHERS: 'FETCH_PENDING_BY_OTHERS'
}